<a href="https://colab.research.google.com/github/shafiqafat/ImplementationOfLinearRegression/blob/main/LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Gluecose-Level-Age.csv to Gluecose-Level-Age.csv


In [3]:
df = pd.read_csv('Gluecose-Level-Age.csv')

In [5]:
df.shape

(6, 2)

In [6]:
x = df[['Age']]
y = df['Gluecose-level']

In [7]:
x

Age
0   43
1   21
2   25
3   42
4   57
5   59

In [8]:
y

0    99
1    65
2    79
3    75
4    87
5    81
Name: Gluecose-level, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = .30,random_state=1)

In [11]:
xtrain

Age
4   57
0   43
3   42
5   59

In [12]:
xtest

Age
2   25
1   21

In [13]:
ytrain

4    87
0    99
3    75
5    81
Name: Gluecose-level, dtype: int64

In [14]:
ytest

2    79
1    65
Name: Gluecose-level, dtype: int64

In [15]:
from sklearn.linear_model import LinearRegression 

In [16]:
reg = LinearRegression()

In [17]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [18]:
reg.predict(xtest)

array([89.71266735, 90.3800206 ])

In [19]:
ytest

2    79
1    65
Name: Gluecose-level, dtype: int64

In [20]:
reg.predict([[53]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([85.04119464])

In [21]:
reg.coef_

array([-0.16683831])

In [22]:
reg.intercept_

93.88362512873326

In [23]:
#y = mx + c
y = -0.16683831 * 59 + 93.88362512873326

In [24]:
y

84.04016483873326